version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
      - npm run build
  build:
    commands:
      - echo La compilaci贸n se complet贸 en `date`
  post_build:
    commands:
      - echo La compilaci贸n se complet贸 en `date`
